/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:f42fcb44-e70d-4a41-95e6-889efdd7a66d",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_IBRoiVY6P",
    "aws_user_pools_web_client_id": "hmdl410a5pd4diakq1mp6cc3i",
    "oauth": {}
};


export default awsmobile;
